//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public long rowid { get; set; }
        public Nullable<long> userId { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> DateOn { get; set; }
    
        public virtual user user { get; set; }
    }
}
